# roles/kubernetes/tasks/containerd.yml
- name: Install containerd package
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Ensure /etc/containerd exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate containerd default config
  command: containerd config default
  register: containerd_default
  changed_when: false

- name: Write containerd config with systemd cgroup enabled
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default.stdout | regex_replace('SystemdCgroup = false','SystemdCgroup = true') }}"
  notify: restart containerd

- name: Ensure containerd is started and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes
