# roles/kubernetes/tasks/kube_packages.yml

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Kubernetes GPG key (ASCII format)
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/Release.key"
    dest: /tmp/kubernetes-release.key
    mode: "0644"

- name: Convert Kubernetes GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/ /
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.apt:
    name:
      - "kubelet={{ k8s_version_full }}"
      - "kubeadm={{ k8s_version_full }}"
      - "kubectl={{ k8s_version_full }}"
    state: present
    force: yes

- name: Hold kubelet, kubeadm and kubectl packages
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl
  changed_when: false

- name: Ensure kubelet service is enabled and started
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes
